In [14]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

print(a,'\n')
print(a[0],'\n')
print(a[1:],'\n')
print(a[1:, 2],'\n')
print(a[1:3, 1:3],'\n')
print(a[::2, ::2],'\n')
print(a[::2],'\n')
print(a[:,2],'\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[1 2 3 4] 

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[ 7 11 15] 

[[ 6  7]
 [10 11]] 

[[ 1  3]
 [ 9 11]] 

[[ 1  2  3  4]
 [ 9 10 11 12]] 

[ 3  7 11 15] 

