## Chapter 3. 파이썬 최고의 라이브러리: 넘파이

### 3.1

#### 1)

In [3]:
import numpy as np

a = np.arange(1,46)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

#### 2)

In [25]:
np.random.seed(85)
np.random.shuffle(a)

lotto = a[0:6]
print(f"lotto: {lotto}")

lotto: [17 34 39 29 16 15]


#### 3)

In [26]:
lotto.sort()
new = a[7]

print(f"lotto: {lotto}, 추가번호: {new}")

lotto: [15 16 17 29 34 39], 추가번호: 8


#### 4)

In [28]:
n_arr = np.arange(25).reshape(5,5)
print(n_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 5)

In [29]:
print(f"첫 원소: {n_arr[0][0]}\n마지막 원소: {n_arr[-1][-1]}\n")

첫 원소: 0
마지막 원소: 24



#### 6)

In [31]:
n_arr2 = n_arr[0:2, 0:]
print(n_arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### 7)

In [32]:
n_arr3 = n_arr[0: , ::2]
print(n_arr3)

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


#### 8)

In [42]:
n_arr4 = n_arr[0:2,0:].reshape(-1)
n_arr4 = np.reshape(n_arr4, (5, 2))
print(f"{n_arr4}")


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### 3.2

In [50]:
a = np.random.randn(8).reshape(2,2,2)
print(f"{a}")

[[[-0.99952508  0.5912005 ]
  [-1.00955693  0.30479321]]

 [[-1.28071705 -0.57713752]
  [ 0.17421722  1.49095478]]]


#### 1)

In [51]:
print(f"a 배열의 최대값: {a.max()}")

a 배열의 최대값: 1.4909547781513464


#### 2)

In [52]:
print(f"a 배열의 최소값: {a.min()}")

a 배열의 최소값: -1.2807170459730393


### 3.3

In [57]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

#### 1) a[:, 1:]

In [58]:
print(f"{a[:, 1:]}")

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]


#### 2) a[0:1, 0:2]

In [59]:
print(f"{a[0:1, 0:2]}")

[[1 2]]


#### 3) a[::2, ::2]

In [60]:
print(f"{a[::2, ::2]}")

[[ 1  3  5]
 [11 13 15]]


### 3.4

#### 1)

In [61]:
a = np.arange(1,26).reshape(5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


#### 2)

In [62]:
print(f"행렬의 행 방향 성분의 합: {np.sum(a, axis=0)}")

행렬의 행 방향 성분의 합: [55 60 65 70 75]


#### 3)

In [64]:
print(f"행렬의 열 방향 성분의 합: {np.sum(a, axis=1)}")

행렬의 열 방향 성분의 합: [ 15  40  65  90 115]


### 3.5

#### 1) reshape(개수, 4행 2열)

In [72]:
a = np.arange(32).reshape(4, 4, 2)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]


#### 2)

In [77]:
a = a.flatten()
print(f"10번째 원소: {a[9]}\n20번째 원소: {a[19]}\n")

10번째 원소: 9
20번째 원소: 19

