In [3]:
num = 100

In [5]:
num = num+100
print (num)

300


## 3장 파이썬 최고의 라이브러리 : 넘파이

### 3.1 파이썬 리스트와 넘파이

In [1]:
import numpy as np      # numpy의 별칭으로 np를 지정함

a = np.array([2, 3, 4]) # 다차원 배열 객체
a

array([2, 3, 4])

### 3.2 파이썬 리스트 vs 넘파이 다차원 배열

In [2]:
store_a = [20, 10, 30]  # 매장 A의 매출 : 파이썬 리스트로 표현
store_b = [70, 90, 70]  # 매장 B의 매출 : 파이썬 리스트로 표현

list_sum = store_a + store_b    # 파이썬 리스트의 더하기 연산
list_sum

[20, 10, 30, 70, 90, 70]

In [3]:
np_store_a = np.array(store_a)  # store_a 리스트를 넘파이 배열로 변환
np_store_b = np.array(store_b)  # store_b 리스트를 넘파이 배열로 변환

array_sum = np_store_a + np_store_b  # 넘파이 배열의 덧셈 결과를 확인하자
array_sum

array([ 90, 100, 100])

### 3.3 다차원 배열의 속성들

In [4]:
a = np.array([2, 3, 4]) # 넘파이 ndarray 객체의 생성

# a 객체의 형상(shape), 차원, 요소의 자료형, 요소의 크기(byte), 요소의 수
a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3,), 1, dtype('int64'), 8, 3)

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]]) # 넘파이 ndarray 객체의 b 생성
b.shape

(2, 3)

In [6]:
a = np.array([10, 20, 30])   # 넘파이 ndarray 객체 a 생성
b = np.array([1, 2, 3])      # 넘파이 ndarray 객체 b 생성
a + b

array([11, 22, 33])

In [8]:
a - b

array([ 9, 18, 27])

In [9]:
a * b

array([10, 40, 90])

In [10]:
a / b

array([10., 10., 10.])

#### NOTE : 넘파이 배열의 데이터 타입(dtype)을 지정하는 두 가지 방법

In [11]:
a = np.array([1, 2, 3, 4], dtype = np.int32)

In [12]:
a = np.array([1, 2, 3, 4], dtype = 'int32')

### 3.4 다차원 배열과 브로드캐스팅

In [13]:
a = np.array([10, 20, 30])
a * 10

array([100, 200, 300])

In [14]:
a + 10

array([20, 30, 40])

In [15]:
b = np.array([[10, 20, 30],
              [40, 50, 60]])
c = np.array([2, 3, 4])
b + c

array([[12, 23, 34],
       [42, 53, 64]])

In [16]:
b * c

array([[ 20,  60, 120],
       [ 80, 150, 240]])

In [17]:
np.zeros((2, 3)) # 2행 3열의 행렬 생성시 모든 값을 0으로

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2, 3)) # 2행 3열의 행렬 생성시 모든 값을 1로

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.full((2, 3), 100) # 2행 3열의 행렬 생성시 모든 값을 100으로

array([[100, 100, 100],
       [100, 100, 100]])

In [20]:
np.eye(3) # 3x3 크기의 단위 행렬 생성

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 3.5 연속적인 값을 가지는 다차원 배열의 생성

In [21]:
np.arange(0, 10) # 0에서 9까지 연속적인 수열을 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0, 10, 2) # 2씩 증가하는 수열을 생성

array([0, 2, 4, 6, 8])

In [23]:
np.arange(0.0, 1.0, 0.2) # 0.2씩 증가하는 수열을 생성

array([0. , 0.2, 0.4, 0.6, 0.8])

In [24]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [26]:
a = np.logspace(0, 5, 6).round(10) # 10^0에서 10^5까지 6개의 수를
a                                  # 로그 스케일 균일한 간격으로 생성한다.

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [27]:
np.log10(a) # a 배열에 로그를 취하면 0, 1, 2, 3, 4, 5가 생성됨

array([0., 1., 2., 3., 4., 5.])

### 3.6 다차원 배열의 축과 삽입

In [28]:
a = np.array([1, 3, 4])
np.insert(a, 1, 2)

array([1, 2, 3, 4])

In [29]:
b = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(b, 1, 4, axis = 0)

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [30]:
np.insert(b, 1, 4, axis = 1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

In [31]:
c = np.array([[1, 2, 3], [4, 5, 6]])
np.flip(c, axis=1)

array([[3, 2, 1],
       [6, 5, 4]])

In [32]:
np.flip(c, axis=0)

array([[4, 5, 6],
       [1, 2, 3]])

### 3.7 넘파이 배열의 인덱싱과 슬라이싱

In [33]:
a = np.array( [[1, 2, 3], [4, 5, 6],
               [7, 8, 9], [0, 1, 2]] )

print(a[0][0])
print(a[2])

1
[7 8 9]


In [34]:
a[1:][0:2]

array([[4, 5, 6],
       [7, 8, 9]])

In [35]:
length0, length1 = a.shape
for i in range(length0):
    for j in range(length1):
        print(a[i][j], a[i, j])

1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
0 0
1 1
2 2


### 3.8 넘파이 스타일의 슬라이싱과 논리 인덱싱

In [36]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [0, 1, 2]])
a[1: , 0:2]

array([[4, 5],
       [7, 8],
       [0, 1]])

In [37]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [38]:
a[ a % 2 == 0 ]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 3.9 다차원 배열의 최대값, 최소값, 평균값 구하기

In [39]:
import numpy as np

a = np.array([10, 20, 30])
a.max(), a.min()           # a 배열원소 중 최대값, 최소값을 출력함

(30, 10)

In [40]:
a.mean()

20.0

In [41]:
a.astype(np.float64)

array([10., 20., 30.])

In [42]:
b = np.array([[1, 1], [2, 2], [3, 3]])
b.flatten() # 넘파이 다차원 배열의 평탄화 메소드

array([1, 1, 2, 2, 3, 3])

In [43]:
b = np.array([[1, 1], [2, 2], [3, 3]])
b.T

array([[1, 2, 3],
       [1, 2, 3]])

In [44]:
c = np.array([35, 24, 55, 69, 19, 99])
c.sort() # 배열의 정렬(오름차순)
c[::-1] # 내림차순 정렬

array([99, 69, 55, 35, 24, 19])

In [45]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort()         # 배열의 정렬, 디폴트 axis는 1
d

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [46]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis=0)   # axis=0 방향 정렬
d

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

### 3.10 다차원 배열을 위한 append() 함수와 행렬 곱셈

In [47]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.append([a], b, axis = 0) # [a]를 통해 2차원 배열로 만들어야 함

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a = [1, 2, 3, 4, 5, 6, 7, 8]     # 1차원 리스트 a
b = np.reshape(a,(2,4)) # 2행4열 행렬 b
c = np.reshape(a,(4,2)) # 4행2열 행렬 c
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
a = np.arange(1,9)   # 1차원 배열 a
b = a.reshape(2,2,2) # 3차원 배열 b
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [52]:
b[0]

array([[1, 2],
       [3, 4]])

In [53]:
a=np.arange(10).reshape(-1,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3.11 과학자들이 사랑하는 수: 난수

In [55]:
def pseudo_rand(x):
    a = 1103515245
    b = 12345
    m = 2 ** 31
    new_x = (a * x + b) % m
    return new_x

seed = 100 # 초기값을 임의로 설정하자

x = pseudo_rand(seed) # seed를 입력으로 하여 새로운 x를 만들자
print(x)
x = pseudo_rand(x) # x_n을 입력으로 하여 새로운 x_(n+1)을 만들자
print(x)

829870797
1533044610


In [56]:
import numpy as np

np.random.rand(5)

array([0.47316211, 0.58888305, 0.91376778, 0.89369874, 0.48826969])

In [57]:
np.random.randint(150, 191, size=10)

array([168, 184, 157, 179, 163, 169, 187, 187, 162, 165])

### 3.11 다양한 난수 만들기 함수를 살펴보자

In [59]:
rnd = np.random.randn(5) * 10 + 165 # 평균값이 165,표준편차가 10인 값 생성
rnd

array([167.24757159, 175.32903597, 174.63682083, 143.81807979,
       162.76777989])

In [60]:
rnd.round(2)       # 소수점 아래 둘째 자리까지 값으로 변환

array([167.25, 175.33, 174.64, 143.82, 162.77])

In [61]:
rnd.astype(int)    # 정수형 자료형으로 변환

array([167, 175, 174, 143, 162])

In [62]:
np.random.seed(42) # 씨드 값이 특정될 경우 매번 동일한 난수의 열이 생성됨

In [63]:
nums = np.random.normal(loc=165, scale=10, size=(3, 4)).round(2)
nums

array([[169.97, 163.62, 171.48, 180.23],
       [162.66, 162.66, 180.79, 172.67],
       [160.31, 170.43, 160.37, 160.34]])

In [64]:
a = np.arange(10)    # 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 값을 생성
np.random.shuffle(a)
a                    # a에는 순서가 뒤섞인 값이 들어있다

array([1, 7, 6, 2, 8, 0, 3, 4, 5, 9])

In [65]:
np.random.permutation([2, 4, 6, 8, 10])

array([ 2, 10,  6,  8,  4])

### 3.12 평균, 분산, 표준편차를 알아보자

In [66]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print('a의 평균값 :', a.mean())

a의 평균값 : 30.0


In [67]:
A = np.array([60, 70, 80, 90, 100])
print('A 모둠의 분산:', np.var(A))

A 모둠의 분산: 200.0


In [68]:
B = np.array([76, 78, 80, 82, 84])
print('B 모둠의 분산:', np.var(B))

B 모둠의 분산: 8.0


### 3.14 벡터화 연산의 성능을 측정해 보자

In [69]:
import numpy as np
import time        # 수행시간 측정을 위하여 time 모듈을 가져온다

arr_a = np.random.rand(100)
arr_b = np.random.rand(100)
result = np.zeros(100)

In [70]:
start = time.time()
for i in range(len(arr_a)):    # 명시적인 작업 지시 : C 스타일
    result[i] = arr_a[i] * arr_b[i]
end = time.time()
print('소요시간: ', end - start)

소요시간:  9.298324584960938e-05


In [71]:
start = time.time()
result = arr_a * arr_b # 벡터화 연산 *
end = time.time()
print('소요시간: ', end - start)
print('소요시간: {:12.10f}'.format(end - start))

소요시간:  0.0006589889526367188
소요시간: 0.0006589890


In [72]:
n_elem = 100000 # 원소의 개수
arr_a = np.random.rand(n_elem)
arr_b = np.random.rand(n_elem)
result = np.zeros(n_elem)

In [73]:
start = time.time()
for i in range(n_elem): # 명시적인 작업 지시 : C 스타일
    result[i] = arr_a[i] * arr_b[i]

end = time.time()
print('원소별 접근 방식 소요시간: ', end - start)

start = time.time()
result = arr_a * arr_b
end = time.time()
print('벡터화 연산 수행 소요시간: ', end - start)

원소별 접근 방식 소요시간:  0.031219959259033203
벡터화 연산 수행 소요시간:  0.0001659393310546875


### 3.15 리덕션 : 배열을 더 강력하게 만드는 기능

In [74]:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
               ])
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
np.sum(arr, axis=(0, 1)) # axis = (0, 1)은 생략 가능

[ 5 10 15 20 25]
[15 15 15 15 15]


75

In [75]:
import numpy as np
import time

n = 1000
arr = np.random.rand(n, n)

In [76]:
sum_naive = 0
start = time.time()
for i in range(n):
    for j in range(n):
        sum_naive += arr[i,j]
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_naive, "\n계산 시간: ", end-start)

1000 x 1000 배열의 원소 합 500020.4230829533 
계산 시간:  0.22484135627746582


In [77]:
start = time.time()
sum_reduction = np.sum(arr, axis = (0,1))
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_reduction,"\n계산 시간: ",end-start)

1000 x 1000 배열의 원소 합 500020.4230829493 
계산 시간:  0.0004038810729980469


### 3.16 배열의 결합 concatenate, vstack, hstack

In [78]:
import numpy as np

a = np.arange(10, 18).reshape(2,4)
a       # (2, 4) 형상의 다차원 배열로 10에서 17까지의 원소를 가짐

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [79]:
b = np.arange(12).reshape(3,4)
b  # (3, 4) 형상의 다차원 배열로 0에서 11까지의 원소를 가짐

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
c = np.arange(8).reshape(2,4)
c   # (2, 4) 형상의 다차원 배열로 0에서 7까지의 원소를 가짐

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [81]:
d = list(range(4))
d   # d는 1차원 리스트로 0에서 3까지의 원소를 가짐

[0, 1, 2, 3]

In [82]:
np.concatenate((a, b))   # a 배열의 마지막 원소 다음에 b 배열을 넣는다

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
np.vstack((a, b)) # a 배열과 b 배열을 수직 방향으로 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
np.vstack((a, d)) # a 배열과 d 리스트의 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3]])

In [85]:
np.vstack((a, b, d)) # 다차원 배열 3개를 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [86]:
np.hstack((a, c))   # 다차원 배열 a, c를 수평으로 결합

array([[10, 11, 12, 13,  0,  1,  2,  3],
       [14, 15, 16, 17,  4,  5,  6,  7]])

In [87]:
# a 배열은 형상이 (2, 4), b 배열은 (3, 4)로 수평 결합이 안됨
np.hstack((a, b)) # a 배열과 b 배열의 hstack 결합-오류

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

### 3.18 배열을 결합하는 r_, c_ 클래스와 column_stack() 함수

In [88]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[10, 20, 30], [40, 50, 60]])

In [89]:
np.r_[a, b]   # a, b 배열을 결합시킴 np.hstack([a, b])와 같다

array([ 1,  2,  3, 10, 20, 30])

In [90]:
np.r_[[a], [b]]

array([[ 1,  2,  3],
       [10, 20, 30]])

In [91]:
np.vstack([a, b])

array([[ 1,  2,  3],
       [10, 20, 30]])

In [92]:
np.r_[a, 4, 5, 6, b] # 중간에 개별 원소 삽입도 가능하다

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30])

In [93]:
np.r_[[0]*3, 5, 6]

array([0, 0, 0, 5, 6])

In [94]:
np.r_[c, d]  # 2차원 배열을 axis=0 방향으로 결합한다

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [95]:
# a, b를 2차원 배열로 만들어서 axis=0 방향으로 결합
np.r_[a.reshape(-1,1), b.reshape(-1,1)]

array([[ 1],
       [ 2],
       [ 3],
       [10],
       [20],
       [30]])

In [96]:
np.concatenate((a.reshape(-1, 1), b.reshape(-1, 1)), axis=1)

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [97]:
np.c_[a, b]

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [98]:
np.column_stack([a, b])

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [99]:
# c와 d의 전치행렬을 결합시킨다
np.concatenate((c.T, d.T), axis=1)

array([[ 1,  4, 10, 40],
       [ 2,  5, 20, 50],
       [ 3,  6, 30, 60]])